In [1]:
import pandas as pd

# 读取Excel文件
file_path = r"E:\【论文】\heritage science\people's commune0609.csv"
df = pd.read_csv(file_path)

In [2]:
df.head()

,专区,市县,COL_C,现今,经度,纬度,海拔,降雨,温度,风力,距运河,距铁路,距海洋,距河流,距公路
0,南京市,南京市,江东,江东街道,118.728495,32.051095,7,0.000033,288.705994,3.69454,0.620123,0.034996,2.28103,0.000000,0.000000
1,南京市,南京市,下关,下关街道,118.756224,32.095841,11,0.000033,288.705994,3.69454,0.577161,0.000000,2.23766,0.028613,0.035866
2,南京市,南京市,玄武,玄武区,118.791547,32.072332,11,0.000033,288.705994,3.69454,0.548046,0.017498,2.20895,0.063981,0.017933
3,南京市,南京市,白下,白下街道,118.787193,32.031171,13,0.000033,288.705994,3.69454,0.559108,0.034996,2.21918,0.060697,0.000000
4,南京市,南京市,鼓楼,鼓楼区,118.760194,32.082754,14,0.000033,288.705994,3.69454,0.577161,0.000000,2.23766,0.040465,0.017933

In [3]:
df['经纬度'] = df['经度'].astype(str) + ',' + df['纬度'].astype(str)

In [4]:
df.head()

,专区,市县,COL_C,现今,经度,纬度,海拔,降雨,温度,风力,距运河,距铁路,距海洋,距河流,距公路,经纬度
0,南京市,南京市,江东,江东街道,118.728495,32.051095,7,0.000033,288.705994,3.69454,0.620123,0.034996,2.28103,0.000000,0.000000,"118.7284949,32.05109453"
1,南京市,南京市,下关,下关街道,118.756224,32.095841,11,0.000033,288.705994,3.69454,0.577161,0.000000,2.23766,0.028613,0.035866,"118.756224,32.095841"
2,南京市,南京市,玄武,玄武区,118.791547,32.072332,11,0.000033,288.705994,3.69454,0.548046,0.017498,2.20895,0.063981,0.017933,"118.7915472,32.07233174"
3,南京市,南京市,白下,白下街道,118.787193,32.031171,13,0.000033,288.705994,3.69454,0.559108,0.034996,2.21918,0.060697,0.000000,"118.7871931,32.03117053"
4,南京市,南京市,鼓楼,鼓楼区,118.760194,32.082754,14,0.000033,288.705994,3.69454,0.577161,0.000000,2.23766,0.040465,0.017933,"118.760194,32.08275366"

In [5]:
columns_to_drop = ['经度', '纬度']
df.drop(columns=columns_to_drop, inplace=True)

In [6]:
df.head()

,专区,市县,COL_C,现今,海拔,降雨,温度,风力,距运河,距铁路,距海洋,距河流,距公路,经纬度
0,南京市,南京市,江东,江东街道,7,0.000033,288.705994,3.69454,0.620123,0.034996,2.28103,0.000000,0.000000,"118.7284949,32.05109453"
1,南京市,南京市,下关,下关街道,11,0.000033,288.705994,3.69454,0.577161,0.000000,2.23766,0.028613,0.035866,"118.756224,32.095841"
2,南京市,南京市,玄武,玄武区,11,0.000033,288.705994,3.69454,0.548046,0.017498,2.20895,0.063981,0.017933,"118.7915472,32.07233174"
3,南京市,南京市,白下,白下街道,13,0.000033,288.705994,3.69454,0.559108,0.034996,2.21918,0.060697,0.000000,"118.7871931,32.03117053"
4,南京市,南京市,鼓楼,鼓楼区,14,0.000033,288.705994,3.69454,0.577161,0.000000,2.23766,0.040465,0.017933,"118.760194,32.08275366"

In [7]:
# 定义一个函数来将数据分为五级
def classify_column(series):
    # 根据数据的值的分布，使用分位数进行分类
    bins = [series.min(), series.quantile(0.2), series.quantile(0.4), series.quantile(0.6), series.quantile(0.8), series.max()]
    labels = [1, 2, 3, 4, 5]
    return pd.cut(series, bins=bins, labels=labels, include_lowest=True)

# 指定需要重新分级的列名
columns_to_classify = ['海拔', '降雨', '温度', '风力', '距运河', '距铁路', '距海洋', '距河流','距公路']

# 对每个列进行分级并创建新列
for col in columns_to_classify:
    df[col + '_level'] = classify_column(df[col])

# 显示处理后的数据，使用Pandas的标准显示方法
df.head()  # 显示前几行数据，你可以调整查看更多行

,专区,市县,COL_C,现今,海拔,降雨,温度,风力,距运河,距铁路,...,经纬度,海拔_level,降雨_level,温度_level,风力_level,距运河_level,距铁路_level,距海洋_level,距河流_level,距公路_level
0,南京市,南京市,江东,江东街道,7,0.000033,288.705994,3.69454,0.620123,0.034996,...,"118.7284949,32.05109453",4,2,5,5,5,1,5,1,1
1,南京市,南京市,下关,下关街道,11,0.000033,288.705994,3.69454,0.577161,0.000000,...,"118.756224,32.095841",4,2,5,5,4,1,5,1,2
2,南京市,南京市,玄武,玄武区,11,0.000033,288.705994,3.69454,0.548046,0.017498,...,"118.7915472,32.07233174",4,2,5,5,4,1,5,2,1
3,南京市,南京市,白下,白下街道,13,0.000033,288.705994,3.69454,0.559108,0.034996,...,"118.7871931,32.03117053",4,2,5,5,4,1,5,2,1
4,南京市,南京市,鼓楼,鼓楼区,14,0.000033,288.705994,3.69454,0.577161,0.000000,...,"118.760194,32.08275366",5,2,5,5,4,1,5,1,1

In [8]:
# 删除原来的列
columns_to_drop = ['海拔', '降雨', '温度', '风力', '距运河', '距铁路', '距海洋', '距河流','距公路']
df.drop(columns=columns_to_drop, inplace=True)

In [9]:
df.head()

,专区,市县,COL_C,现今,经纬度,海拔_level,降雨_level,温度_level,风力_level,距运河_level,距铁路_level,距海洋_level,距河流_level,距公路_level
0,南京市,南京市,江东,江东街道,"118.7284949,32.05109453",4,2,5,5,5,1,5,1,1
1,南京市,南京市,下关,下关街道,"118.756224,32.095841",4,2,5,5,4,1,5,1,2
2,南京市,南京市,玄武,玄武区,"118.7915472,32.07233174",4,2,5,5,4,1,5,2,1
3,南京市,南京市,白下,白下街道,"118.7871931,32.03117053",4,2,5,5,4,1,5,2,1
4,南京市,南京市,鼓楼,鼓楼区,"118.760194,32.08275366",5,2,5,5,4,1,5,1,1

In [10]:
# 重新命名 '海拔_level' 列的分级值
elevation_level_mapping = {
    1: '海拔低',
    2: '海拔较低',
    3: '海拔适中',
    4: '海拔较高',
    5: '海拔高'
}

# 映射并重命名列为 '海拔'
df['海拔'] = df['海拔_level'].map(elevation_level_mapping)

# 显示更新后的 DataFrame，检查是否正确
df.head()

,专区,市县,COL_C,现今,经纬度,海拔_level,降雨_level,温度_level,风力_level,距运河_level,距铁路_level,距海洋_level,距河流_level,距公路_level,海拔
0,南京市,南京市,江东,江东街道,"118.7284949,32.05109453",4,2,5,5,5,1,5,1,1,海拔较高
1,南京市,南京市,下关,下关街道,"118.756224,32.095841",4,2,5,5,4,1,5,1,2,海拔较高
2,南京市,南京市,玄武,玄武区,"118.7915472,32.07233174",4,2,5,5,4,1,5,2,1,海拔较高
3,南京市,南京市,白下,白下街道,"118.7871931,32.03117053",4,2,5,5,4,1,5,2,1,海拔较高
4,南京市,南京市,鼓楼,鼓楼区,"118.760194,32.08275366",5,2,5,5,4,1,5,1,1,海拔高

In [11]:
# 重新命名 '降雨_level' 列的分级值
rainfall_level_mapping = {
    1: '降雨少',
    2: '降雨较少',
    3: '降雨适中',
    4: '降雨较多',
    5: '降雨多'
}

# 映射并重命名列为 '海拔'
df['降雨'] = df['降雨_level'].map(rainfall_level_mapping)

# 显示更新后的 DataFrame，检查是否正确
df.head()

,专区,市县,COL_C,现今,经纬度,海拔_level,降雨_level,温度_level,风力_level,距运河_level,距铁路_level,距海洋_level,距河流_level,距公路_level,海拔,降雨
0,南京市,南京市,江东,江东街道,"118.7284949,32.05109453",4,2,5,5,5,1,5,1,1,海拔较高,降雨较少
1,南京市,南京市,下关,下关街道,"118.756224,32.095841",4,2,5,5,4,1,5,1,2,海拔较高,降雨较少
2,南京市,南京市,玄武,玄武区,"118.7915472,32.07233174",4,2,5,5,4,1,5,2,1,海拔较高,降雨较少
3,南京市,南京市,白下,白下街道,"118.7871931,32.03117053",4,2,5,5,4,1,5,2,1,海拔较高,降雨较少
4,南京市,南京市,鼓楼,鼓楼区,"118.760194,32.08275366",5,2,5,5,4,1,5,1,1,海拔高,降雨较少

In [13]:
# 重新命名 '温度_level' 列的分级值
temp_level_mapping = {
    1: '气温低',
    2: '气温较低',
    3: '气温适中',
    4: '气温较高',
    5: '气温高'
}

# 映射并重命名列为 '海拔'
df['气温'] = df['温度_level'].map(temp_level_mapping)

# 显示更新后的 DataFrame，检查是否正确
df.head()

,专区,市县,COL_C,现今,经纬度,海拔_level,降雨_level,温度_level,风力_level,距运河_level,距铁路_level,距海洋_level,距河流_level,距公路_level,海拔,降雨,气温
0,南京市,南京市,江东,江东街道,"118.7284949,32.05109453",4,2,5,5,5,1,5,1,1,海拔较高,降雨较少,气温高
1,南京市,南京市,下关,下关街道,"118.756224,32.095841",4,2,5,5,4,1,5,1,2,海拔较高,降雨较少,气温高
2,南京市,南京市,玄武,玄武区,"118.7915472,32.07233174",4,2,5,5,4,1,5,2,1,海拔较高,降雨较少,气温高
3,南京市,南京市,白下,白下街道,"118.7871931,32.03117053",4,2,5,5,4,1,5,2,1,海拔较高,降雨较少,气温高
4,南京市,南京市,鼓楼,鼓楼区,"118.760194,32.08275366",5,2,5,5,4,1,5,1,1,海拔高,降雨较少,气温高

In [14]:
# 重新命名 '风力_level' 列的分级值
wind_level_mapping = {
    1: '风力弱',
    2: '风力较弱',
    3: '风力适中',
    4: '风力较强',
    5: '风力强'
}

# 映射并重命名列为 '海拔'
df['风力'] = df['风力_level'].map(wind_level_mapping)

# 显示更新后的 DataFrame，检查是否正确
df.head()

,专区,市县,COL_C,现今,经纬度,海拔_level,降雨_level,温度_level,风力_level,距运河_level,距铁路_level,距海洋_level,距河流_level,距公路_level,海拔,降雨,气温,风力
0,南京市,南京市,江东,江东街道,"118.7284949,32.05109453",4,2,5,5,5,1,5,1,1,海拔较高,降雨较少,气温高,风力强
1,南京市,南京市,下关,下关街道,"118.756224,32.095841",4,2,5,5,4,1,5,1,2,海拔较高,降雨较少,气温高,风力强
2,南京市,南京市,玄武,玄武区,"118.7915472,32.07233174",4,2,5,5,4,1,5,2,1,海拔较高,降雨较少,气温高,风力强
3,南京市,南京市,白下,白下街道,"118.7871931,32.03117053",4,2,5,5,4,1,5,2,1,海拔较高,降雨较少,气温高,风力强
4,南京市,南京市,鼓楼,鼓楼区,"118.760194,32.08275366",5,2,5,5,4,1,5,1,1,海拔高,降雨较少,气温高,风力强

In [15]:
# 重新命名 '距运河_level' 列的分级值
canal_level_mapping = {
    1: '距离运河近',
    2: '距离运河较近',
    3: '距离运河适中',
    4: '距离运河远',
    5: '距离运河较远'
}

# 映射并重命名列为 '海拔'
df['至运河距离'] = df['距运河_level'].map(canal_level_mapping)

# 显示更新后的 DataFrame，检查是否正确
df.head()

,专区,市县,COL_C,现今,经纬度,海拔_level,降雨_level,温度_level,风力_level,距运河_level,距铁路_level,距海洋_level,距河流_level,距公路_level,海拔,降雨,气温,风力,至运河距离
0,南京市,南京市,江东,江东街道,"118.7284949,32.05109453",4,2,5,5,5,1,5,1,1,海拔较高,降雨较少,气温高,风力强,距离运河较远
1,南京市,南京市,下关,下关街道,"118.756224,32.095841",4,2,5,5,4,1,5,1,2,海拔较高,降雨较少,气温高,风力强,距离运河远
2,南京市,南京市,玄武,玄武区,"118.7915472,32.07233174",4,2,5,5,4,1,5,2,1,海拔较高,降雨较少,气温高,风力强,距离运河远
3,南京市,南京市,白下,白下街道,"118.7871931,32.03117053",4,2,5,5,4,1,5,2,1,海拔较高,降雨较少,气温高,风力强,距离运河远
4,南京市,南京市,鼓楼,鼓楼区,"118.760194,32.08275366",5,2,5,5,4,1,5,1,1,海拔高,降雨较少,气温高,风力强,距离运河远

In [16]:
# 重新命名 '距铁路_level' 列的分级值
railway_level_mapping = {
    1: '距离铁路近',
    2: '距离铁路较近',
    3: '距离铁路适中',
    4: '距离铁路远',
    5: '距离铁路较远'
}

# 映射并重命名列为 '海拔'
df['至铁路距离'] = df['距铁路_level'].map(railway_level_mapping)

# 显示更新后的 DataFrame，检查是否正确
df.head()

,专区,市县,COL_C,现今,经纬度,海拔_level,降雨_level,温度_level,风力_level,距运河_level,距铁路_level,距海洋_level,距河流_level,距公路_level,海拔,降雨,气温,风力,至运河距离,至铁路距离
0,南京市,南京市,江东,江东街道,"118.7284949,32.05109453",4,2,5,5,5,1,5,1,1,海拔较高,降雨较少,气温高,风力强,距离运河较远,距离铁路近
1,南京市,南京市,下关,下关街道,"118.756224,32.095841",4,2,5,5,4,1,5,1,2,海拔较高,降雨较少,气温高,风力强,距离运河远,距离铁路近
2,南京市,南京市,玄武,玄武区,"118.7915472,32.07233174",4,2,5,5,4,1,5,2,1,海拔较高,降雨较少,气温高,风力强,距离运河远,距离铁路近
3,南京市,南京市,白下,白下街道,"118.7871931,32.03117053",4,2,5,5,4,1,5,2,1,海拔较高,降雨较少,气温高,风力强,距离运河远,距离铁路近
4,南京市,南京市,鼓楼,鼓楼区,"118.760194,32.08275366",5,2,5,5,4,1,5,1,1,海拔高,降雨较少,气温高,风力强,距离运河远,距离铁路近

In [17]:
# 重新命名分级值
sea_level_mapping = {
    1: '距离海洋近',
    2: '距离海洋较近',
    3: '距离海洋适中',
    4: '距离海洋远',
    5: '距离海洋较远'
}
river_level_mapping = {
    1: '距离河流近',
    2: '距离河流较近',
    3: '距离河流适中',
    4: '距离河流远',
    5: '距离河流较远'
}
road_level_mapping = {
    1: '距离公路近',
    2: '距离公路较近',
    3: '距离公路适中',
    4: '距离公路远',
    5: '距离公路较远'
}

# 映射并重命名列为 '海拔'
df['至海洋距离'] = df['距海洋_level'].map(sea_level_mapping)
df['至河流距离'] = df['距河流_level'].map(river_level_mapping)
df['至公路距离'] = df['距公路_level'].map(road_level_mapping)
# 显示更新后的 DataFrame，检查是否正确
df.head()

,专区,市县,COL_C,现今,经纬度,海拔_level,降雨_level,温度_level,风力_level,距运河_level,...,距公路_level,海拔,降雨,气温,风力,至运河距离,至铁路距离,至海洋距离,至河流距离,至公路距离
0,南京市,南京市,江东,江东街道,"118.7284949,32.05109453",4,2,5,5,5,...,1,海拔较高,降雨较少,气温高,风力强,距离运河较远,距离铁路近,距离海洋较远,距离河流近,距离公路近
1,南京市,南京市,下关,下关街道,"118.756224,32.095841",4,2,5,5,4,...,2,海拔较高,降雨较少,气温高,风力强,距离运河远,距离铁路近,距离海洋较远,距离河流近,距离公路较近
2,南京市,南京市,玄武,玄武区,"118.7915472,32.07233174",4,2,5,5,4,...,1,海拔较高,降雨较少,气温高,风力强,距离运河远,距离铁路近,距离海洋较远,距离河流较近,距离公路近
3,南京市,南京市,白下,白下街道,"118.7871931,32.03117053",4,2,5,5,4,...,1,海拔较高,降雨较少,气温高,风力强,距离运河远,距离铁路近,距离海洋较远,距离河流较近,距离公路近
4,南京市,南京市,鼓楼,鼓楼区,"118.760194,32.08275366",5,2,5,5,4,...,1,海拔高,降雨较少,气温高,风力强,距离运河远,距离铁路近,距离海洋较远,距离河流近,距离公路近

In [18]:
# 删除原来的列
columns_to_drop = ['海拔_level', '降雨_level', '温度_level', '风力_level', '距运河_level', '距铁路_level', '距海洋_level', '距河流_level','距公路_level']
df.drop(columns=columns_to_drop, inplace=True)
df.head()

,专区,市县,COL_C,现今,经纬度,海拔,降雨,气温,风力,至运河距离,至铁路距离,至海洋距离,至河流距离,至公路距离
0,南京市,南京市,江东,江东街道,"118.7284949,32.05109453",海拔较高,降雨较少,气温高,风力强,距离运河较远,距离铁路近,距离海洋较远,距离河流近,距离公路近
1,南京市,南京市,下关,下关街道,"118.756224,32.095841",海拔较高,降雨较少,气温高,风力强,距离运河远,距离铁路近,距离海洋较远,距离河流近,距离公路较近
2,南京市,南京市,玄武,玄武区,"118.7915472,32.07233174",海拔较高,降雨较少,气温高,风力强,距离运河远,距离铁路近,距离海洋较远,距离河流较近,距离公路近
3,南京市,南京市,白下,白下街道,"118.7871931,32.03117053",海拔较高,降雨较少,气温高,风力强,距离运河远,距离铁路近,距离海洋较远,距离河流较近,距离公路近
4,南京市,南京市,鼓楼,鼓楼区,"118.760194,32.08275366",海拔高,降雨较少,气温高,风力强,距离运河远,距离铁路近,距离海洋较远,距离河流近,距离公路近

In [ ]:
# 将处理好的 DataFrame 输出到新的 CSV 文件
output_file_path = r"E:\【论文】\heritage science\0609Chinese_knowledge_graph\0609processed_data.csv"  # 设置文件路径

# 正确保存 CSV 文件，防止中文乱码
df.to_csv(output_file_path, index=False, encoding='utf-8-sig')

In [25]:
import pandas as pd

# 读取 CSV 文件
df = pd.read_csv(r"E:\【论文】\heritage science\0609Chinese_knowledge_graph\0609processed_data.csv")

In [27]:
# 创建一个空的列表，用于存储三元组数据
triples = []

# 遍历 DataFrame 的每一行
for index, row in df.iterrows():
    head = row['COL_C']
    location = row['经纬度']
    
    # 需要转化为关系的列（不包括head和location）
    relations = ['专区', '市县', '现今', '海拔', '降雨', '气温', '风力', '至运河距离', '至铁路距离', '至海洋距离', '至河流距离', '至公路距离']
    
    # 遍历关系列并构造三元组
    for relation in relations:
        tail = row[relation]
        triples.append([head, tail, relation, location])

# 将三元组数据转化为 DataFrame
triples_df = pd.DataFrame(triples, columns=['head', 'tail', 'relation', 'location'])

In [28]:
triples_df

      head    tail relation                 location
0       江东     南京市       专区  118.7284949,32.05109453
1       江东     南京市       市县  118.7284949,32.05109453
2       江东    江东街道       现今  118.7284949,32.05109453
3       江东    海拔较高       海拔  118.7284949,32.05109453
4       江东    降雨较少       降雨  118.7284949,32.05109453
...    ...     ...      ...                      ...
4003  东山洞庭  距离运河适中    至运河距离  120.3794089,31.05707673
4004  东山洞庭  距离铁路适中    至铁路距离  120.3794089,31.05707673
4005  东山洞庭  距离海洋适中    至海洋距离  120.3794089,31.05707673
4006  东山洞庭   距离河流近    至河流距离  120.3794089,31.05707673
4007  东山洞庭  距离公路较远    至公路距离  120.3794089,31.05707673

[4008 rows x 4 columns]

In [ ]:
# 保存为新的 CSV 文件
triples_df.to_csv(r"E:\【论文】\heritage science\0609Chinese_knowledge_graph\0609三元组.csv", index=False)

# 显示部分结果
print(triples_df.head())

  head  tail relation                 location
0   江东   南京市       专区  118.7284949,32.05109453
1   江东   南京市       市县  118.7284949,32.05109453
2   江东  江东街道       现今  118.7284949,32.05109453
3   江东  海拔较高       海拔  118.7284949,32.05109453
4   江东  降雨较少       降雨  118.7284949,32.05109453

In [30]:
import pandas as pd

# 读取含 location 的 CSV 文件
df_location = pd.read_csv(r"E:\【论文】\heritage science\0609Chinese_knowledge_graph\0609三元组.csv")

# 读取缺少 location 的 Excel 文件
df_new = pd.read_excel(r"E:\people's commune_classified.xlsx")

In [31]:
# 提取需要的列
df_location = df_location[['head', 'tail', 'relation', 'location']].drop_duplicates()
df_new = df_new[['head', 'tail', 'relation']]  # 此文件无 location 列

# 构建 head → location 映射
head_location_mapping = df_location[['head', 'location']].drop_duplicates()

# 合并：按 head 补充 location
df_merged = pd.merge(df_new, head_location_mapping, on='head', how='left')

# 重新排列列顺序为 head, tail, relation, location
df_merged = df_merged[['head', 'tail', 'relation', 'location']]

In [32]:
# 保存结果为新文件（可选）
df_merged.to_csv(r"E:\【论文】\heritage science\0609Chinese_knowledge_graph\0609三元组（含经纬度、产业）.csv", index=False, encoding='utf-8-sig')

# 显示部分结果以验证
df_merged.head()

  head tail relation                 location
0   江东   肥料       农业  118.7284949,32.05109453
1   下关   养猪       农业     118.756224,32.095841
2   下关   蔬菜       农业     118.756224,32.095841
3   下关   养鱼       农业     118.756224,32.095841
4   下关   养禽       农业     118.756224,32.095841